---
- name: Deploy My Application
  hosts: my_servers
  become: yes

  tasks:
    - name: Update package list
      apt:
        update_cache: yes
    
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - python3
        - python3-pip
    
    - name: Clone the application repository
      git:
        repo: 'https://github.com/yourusername/yourapp.git'
        dest: /var/www/yourapp
    
    - name: Install application dependencies
      pip:
        requirements: /var/www/yourapp/requirements.txt