---
- name: Ensure Apache is installed and running
  hosts: my_servers
  become: yes
  
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes
    
    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
