---
- hosts: ec2_instances
  become: yes
  tasks:
    - name: Set SSH password for ec2-user
      user:
        name: ec2-user
        password: "{{ 'YourSecurePasswordHere' | password_hash('sha512') }}"
