
- name: Disable NodeJs default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable Nodejs 20 module
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Insaling Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: latest

- name: Set up pre-requisits
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Download Nodejs dependencies
  ansible.builtin.shell: npm install # check fore node js module
  args:               
    chdir: "{{ app_path }}" #change directory and npm install

- name: load schema
  ansible.builtin.include_role:
    name: common
    tasks_from: schema

- name: System setp
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd